In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import requests
import json

In [19]:
csv_filename = 'monthly_sales_data.csv'
# Read the CSV file from the specified path
full_path = os.path.join(r'data', csv_filename)
df = pd.read_csv(full_path)
df.head()

,sku name,sku nbr,state territory code,sub class,region,sales units,month
0,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0,2025-12-01
1,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,-1.0,2026-03-01
2,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0,2025-02-01
3,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,3.0,2026-01-01
4,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0,2025-10-01

In [24]:
df_monthly_sales_data = df.copy()

In [26]:
df_monthly_sales_data = df_monthly_sales_data.rename(columns={
    'sku name': 'sku_name', 
    'sku nbr': 'sku_nbr', 
    'sales units': 'sales_units',
    'state territory code': 'state_territory_code',
    'sub class': 'sub_class',    
})
df_monthly_sales_data.head()

,sku_name,sku_nbr,state_territory_code,sub_class,region,sales_units,month
0,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0,2025-12-01
1,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,-1.0,2026-03-01
2,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0,2025-02-01
3,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,3.0,2026-01-01
4,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0,2025-10-01

In [38]:
df_monthly_sales_data['sku_nbr'].nunique()

905

In [9]:
import os

print(os.path.abspath("config.json"))

with open("config.json", "r") as f:
    print(repr(f.read()))

c:\Users\TobyWong\Desktop\UNCC\6211\advanced_business_analytics\config.json
'{\n  "FRED_API_KEY": "8a8f9ab6bab1b068658f888aad3dce92"\n}'

In [32]:
API_KEY = "8a8f9ab6bab1b068658f888aad3dce92"
BASE_URL = "https://api.stlouisfed.org/fred/series/observations"


def get_fred_series(series_id):
    params = {
        "series_id": series_id,
        "api_key": API_KEY,
        "file_type": "json",
    }
    response = requests.get(BASE_URL, params=params, timeout=30)
    response.raise_for_status()

    data = response.json()
    df = pd.DataFrame(data["observations"])[["date", "value"]]
    df["date"] = pd.to_datetime(df["date"])
    df["value"] = pd.to_numeric(df["value"], errors="coerce")
    df = df.rename(columns={"date": "month", "value": series_id})
    return df


def add_transforms(df, col):
    df = df.copy()

    # raw
    df[f"{col}_level"] = df[col]

    # month-over-month percent change
    df[f"{col}_pct_1m"] = df[col].pct_change()

    # year-over-year percent change
    df[f"{col}_pct_12m"] = df[col].pct_change(12)

    # first difference
    df[f"{col}_diff_1m"] = df[col].diff()

    # rolling means
    df[f"{col}_roll3"] = df[col].rolling(3).mean()
    df[f"{col}_roll6"] = df[col].rolling(6).mean()

    return df


def add_lags(df, col_list, lags=(0, 1, 3, 6)):
    df = df.copy()
    for col in col_list:
        for lag in lags:
            df[f"{col}_lag{lag}"] = df[col].shift(lag)
    return df


# ----------------------------
# 1. Prepare monthly SKU sales
# ----------------------------
df = df_monthly_sales_data.copy()
df["month"] = pd.to_datetime(df["month"])

df_sales = (
    df.groupby(["sku_nbr", "month"], as_index=False)["sales_units"]
      .sum()
      .sort_values(["sku_nbr", "month"])
)

# Add transforms for sales within each SKU
df_sales["sales_level"] = df_sales["sales_units"]
df_sales["sales_pct_1m"] = df_sales.groupby("sku_nbr")["sales_units"].pct_change()
df_sales["sales_pct_12m"] = df_sales.groupby("sku_nbr")["sales_units"].pct_change(12)
df_sales["sales_diff_1m"] = df_sales.groupby("sku_nbr")["sales_units"].diff()
df_sales["sales_roll3"] = (
    df_sales.groupby("sku_nbr")["sales_units"]
    .transform(lambda s: s.rolling(3).mean())
)
df_sales["sales_roll6"] = (
    df_sales.groupby("sku_nbr")["sales_units"]
    .transform(lambda s: s.rolling(6).mean())
)

# ----------------------------
# 2. Pull FRED data
# ----------------------------
df_houst = get_fred_series("HOUST")
df_computsa = get_fred_series("COMPUTSA")

df_fred = df_houst.merge(df_computsa, on="month", how="outer").sort_values("month")

# Add transforms for FRED columns
for fred_col in ["HOUST", "COMPUTSA"]:
    df_fred = add_transforms(df_fred, fred_col)

fred_feature_cols = [c for c in df_fred.columns if c != "month"]

# Add lagged versions of all FRED transformed columns
df_fred = add_lags(df_fred, fred_feature_cols, lags=(0, 1, 3, 6))

# Keep only lagged feature columns
fred_lag_cols = [c for c in df_fred.columns if c != "month" and "_lag" in c]

# ----------------------------
# 3. Merge sales + FRED
# ----------------------------
df_model = df_sales.merge(df_fred[["month"] + fred_lag_cols], on="month", how="left")

# ----------------------------
# 4. Run correlation search
# ----------------------------
sales_features = [
    "sales_level",
    "sales_pct_1m",
    "sales_pct_12m",
    "sales_diff_1m",
    "sales_roll3",
    "sales_roll6",
]

results = []

for sku, g in df_model.groupby("sku_nbr"):
    for sales_col in sales_features:
        for fred_col in fred_lag_cols:
            temp = g[[sales_col, fred_col]].dropna()

            if len(temp) < 12:
                continue

            corr = temp[sales_col].corr(temp[fred_col])

            results.append({
                "sku_nbr": sku,
                "sales_feature": sales_col,
                "fred_feature": fred_col,
                "correlation": corr,
                "abs_correlation": abs(corr),
                "n_obs": len(temp),
            })

df_corr_results = pd.DataFrame(results)

# ----------------------------
# 5. Best result per SKU
# ----------------------------
df_best_per_sku = (
    df_corr_results
    .sort_values(["sku_nbr", "abs_correlation"], ascending=[True, False])
    .groupby("sku_nbr", as_index=False)
    .first()
)

print(df_best_per_sku.head(20))

c:\Users\TobyWong\Desktop\UNCC\6211\advanced_business_analytics\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:2882: RuntimeWarning: invalid value encountered in subtract
  X -= avg[:, None]
c:\Users\TobyWong\Desktop\UNCC\6211\advanced_business_analytics\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:2887: RuntimeWarning: invalid value encountered in dot
  c = dot(X, X_T.conj())
c:\Users\TobyWong\Desktop\UNCC\6211\advanced_business_analytics\.venv\Lib\site-packages\numpy\_core\_methods.py:132: RuntimeWarning: invalid value encountered in reduce
  ret = umr_sum(arr, axis, dtype, out, keepdims, where=where)

    sku_nbr  sales_feature           fred_feature  correlation  \
0    110241    sales_roll6    COMPUTSA_roll6_lag3     0.775823
1    110269    sales_roll6  COMPUTSA_pct_12m_lag3     0.662000
2    110630    sales_roll6    COMPUTSA_roll3_lag0    -0.606411
3    110661    sales_roll6       HOUST_roll6_lag3     0.629597
4    110689  sales_pct_12m    COMPUTSA_roll3_lag6     0.579756
5    113053    sales_roll6    COMPUTSA_roll3_lag1    -0.540596
6    120088    sales_roll6       HOUST_roll3_lag0    -0.470935
7    134633    sales_roll3  COMPUTSA_pct_12m_lag3     0.646949
8    134634    sales_roll3  COMPUTSA_pct_12m_lag3     0.658114
9    142559  sales_pct_12m    COMPUTSA_roll3_lag0     0.696430
10   144650    sales_roll6             HOUST_lag0    -0.442583
11   144700    sales_roll6       HOUST_roll3_lag0    -0.527347
12   144745  sales_pct_12m  COMPUTSA_pct_12m_lag0    -0.605345
13   145587    sales_roll3       HOUST_roll6_lag3     0.643513
14   145590    sales_roll6    COMPUTSA_roll6_lag3     0.764938
15   145668  sales_pct_12m          COMPUTSA_lag6     0.692370
16   145766  sales_pct_12m  COMPUTSA_pct_12m_lag6     0.661166
17   147075    sales_roll6       HOUST_roll6_lag0    -0.705243
18   147103    sales_roll6    COMPUTSA_roll6_lag0    -0.878546
19   161035  sales_pct_12m    COMPUTSA_roll6_lag6     0.593437

    abs_correlation  n_obs
0          0.775823     32
1          0.662000     32
2          0.606411     32
3          0.629597     32
4          0.579756     25
5          0.540596     32
6          0.470935     32
7          0.646949     35
8          0.658114     35
9          0.696430     25
10         0.442583     32
11         0.527347     32
12         0.605345     25
13         0.643513     35
14         0.764938     32
15         0.692370     25
16         0.661166     25
17         0.705243     32
18         0.878546     17
19         0.593437     25

In [33]:
print(
    df_corr_results
    .sort_values("abs_correlation", ascending=False)
    .head(50)
)

           sku_nbr  sales_feature         fred_feature  correlation  \
267733  1011642227    sales_roll6  COMPUTSA_roll6_lag1    -0.978452
267732  1011642227    sales_roll6  COMPUTSA_roll6_lag0    -0.975832
187654      760407    sales_roll6  COMPUTSA_roll6_lag3     0.957093
267729  1011642227    sales_roll6  COMPUTSA_roll3_lag1    -0.953121
267730  1011642227    sales_roll6  COMPUTSA_roll3_lag3    -0.951251
120732      394909    sales_roll6  COMPUTSA_roll6_lag0    -0.950348
235253  1002347266    sales_roll6  COMPUTSA_roll6_lag1     0.950057
267454  1011642044    sales_roll6  COMPUTSA_roll6_lag3    -0.947159
267453  1011642044    sales_roll6  COMPUTSA_roll6_lag1    -0.940325
226046  1000540457    sales_roll6     HOUST_roll6_lag3    -0.935558
120728      394909    sales_roll6  COMPUTSA_roll3_lag0    -0.932042
238221  1003179849    sales_roll6  COMPUTSA_roll6_lag1    -0.929830
267450  1011642044    sales_roll6  COMPUTSA_roll3_lag3    -0.928899
235250  1002347266    sales_roll6  COMPUTSA_roll3_lag3     0.925993
267452  1011642044    sales_roll6  COMPUTSA_roll6_lag0    -0.923126
267728  1011642227    sales_roll6  COMPUTSA_roll3_lag0    -0.922744
267672  1011642227    sales_roll3  COMPUTSA_roll3_lag0    -0.922693
92231       295080    sales_roll3  COMPUTSA_roll6_lag6     0.917389
259780  1004509341    sales_roll6  COMPUTSA_roll6_lag0     0.917104
120729      394909    sales_roll6  COMPUTSA_roll3_lag1    -0.915114
267734  1011642227    sales_roll6  COMPUTSA_roll6_lag3    -0.914180
267676  1011642227    sales_roll3  COMPUTSA_roll6_lag0    -0.913719
120733      394909    sales_roll6  COMPUTSA_roll6_lag1    -0.913352
26149       188336    sales_roll6  COMPUTSA_roll6_lag1     0.912984
247065  1004059425    sales_roll6  COMPUTSA_roll3_lag1     0.911231
121236      426540  sales_pct_12m  COMPUTSA_roll6_lag0    -0.910982
187597      760407    sales_roll3  COMPUTSA_roll6_lag1     0.910860
247068  1004059425    sales_roll6  COMPUTSA_roll6_lag0     0.908667
252951  1004159412    sales_roll6  COMPUTSA_roll6_lag6     0.908416
66409       193763    sales_roll6  COMPUTSA_roll3_lag1    -0.907629
66412       193763    sales_roll6  COMPUTSA_roll6_lag0    -0.904272
130757      472638    sales_roll6  COMPUTSA_roll6_lag1     0.902480
66413       193763    sales_roll6  COMPUTSA_roll6_lag1    -0.902227
115414      377033    sales_roll6  COMPUTSA_roll6_lag3     0.900474
267449  1011642044    sales_roll6  COMPUTSA_roll3_lag1    -0.898786
187594      760407    sales_roll3  COMPUTSA_roll3_lag3     0.897999
238218  1003179849    sales_roll6  COMPUTSA_roll3_lag3    -0.897145
258412  1004509332    sales_roll6     HOUST_roll6_lag0    -0.893748
226071  1000540457    sales_roll6  COMPUTSA_roll6_lag6     0.893095
238220  1003179849    sales_roll6  COMPUTSA_roll6_lag0    -0.892209
29005       188425  sales_pct_12m  COMPUTSA_roll6_lag1     0.892018
121406      426540    sales_roll6  COMPUTSA_roll6_lag3    -0.891984
115411      377033    sales_roll6  COMPUTSA_roll3_lag6     0.890831
238222  1003179849    sales_roll6  COMPUTSA_roll6_lag3    -0.890135
267673  1011642227    sales_roll3  COMPUTSA_roll3_lag1    -0.889815
24807       188271    sales_roll6  COMPUTSA_roll6_lag6     0.889128
26146       188336    sales_roll6  COMPUTSA_roll3_lag3     0.888172
120730      394909    sales_roll6  COMPUTSA_roll3_lag3    -0.886311
121237      426540  sales_pct_12m  COMPUTSA_roll6_lag1    -0.885508
235252  1002347266    sales_roll6  COMPUTSA_roll6_lag0     0.885053

        abs_correlation  n_obs
267733         0.978452     17
267732         0.975832     17
187654         0.957093     32
267729         0.953121     17
267730         0.951251     17
120732         0.950348     14
235253         0.950057     19
267454         0.947159     15
267453         0.940325     15
226046         0.935558     12
120728         0.932042     14
238221         0.929830     13
267450         0.928899     15
235250         0.925993     19
267452         0.923126     15
267728         0.922744     17
267672         0.922693     20
92231          0.917389     35
259780         0.917104     20
120729         0.915114     14
267734         0.914180     17
267676         0.913719     20
120733         0.913352     14
26149          0.912984     32
247065         0.911231     16
121236         0.910982     25
187597         0.910860     35
247068         0.908667     16
252951         0.908416     25
66409          0.907629     15
66412          0.904272     15
130757         0.902480     32
66413          0.902227     15
115414         0.900474     32
267449         0.898786     15
187594         0.897999     35
238218         0.897145     13
258412         0.893748     32
226071         0.893095     12
238220         0.892209     13
29005          0.892018     25
121406         0.891984     32
115411         0.890831     32
238222         0.890135     13
267673         0.889815     20
24807          0.889128     32
26146          0.888172     32
120730         0.886311     14
121237         0.885508     25
235252         0.885053     19

In [40]:
def get_fred_series(series_id: str) -> pd.DataFrame:
    params = {
        "series_id": series_id,
        "api_key": API_KEY,
        "file_type": "json",
    }

    response = requests.get(BASE_URL, params=params, timeout=30)
    response.raise_for_status()

    data = response.json()
    df = pd.DataFrame(data["observations"])[["date", "value"]]
    df["date"] = pd.to_datetime(df["date"])
    df["value"] = pd.to_numeric(df["value"], errors="coerce")

    return df.rename(columns={"date": "month", "value": series_id})


def add_fred_features(df_fred: pd.DataFrame, col: str, lags=(0, 1, 3, 6)) -> pd.DataFrame:
    df_fred = df_fred.copy()

    # Base transforms
    df_fred[f"{col}_level"] = df_fred[col]
    df_fred[f"{col}_pct_1m"] = df_fred[col].pct_change()
    df_fred[f"{col}_pct_12m"] = df_fred[col].pct_change(12)
    df_fred[f"{col}_roll3"] = df_fred[col].rolling(3).mean()

    base_cols = [
        f"{col}_level",
        f"{col}_pct_1m",
        f"{col}_pct_12m",
        f"{col}_roll3",
    ]

    # Lagged versions
    for base_col in base_cols:
        for lag in lags:
            df_fred[f"{base_col}_lag{lag}"] = df_fred[base_col].shift(lag)

    return df_fred


def prepare_sales_features(df_sales: pd.DataFrame) -> pd.DataFrame:
    df_sales = df_sales.copy()
    df_sales = df_sales.sort_values(["sku_nbr", "month"])

    df_sales["sales_level"] = df_sales["sales_units"]
    df_sales["sales_pct_1m"] = df_sales.groupby("sku_nbr")["sales_units"].pct_change()
    df_sales["sales_pct_12m"] = df_sales.groupby("sku_nbr")["sales_units"].pct_change(12)
    df_sales["sales_roll3"] = (
        df_sales.groupby("sku_nbr")["sales_units"]
        .transform(lambda s: s.rolling(3).mean())
    )

    return df_sales


def run_sku_correlation_analysis(
    df_monthly_sales_data: pd.DataFrame,
    min_obs: int = 18,
    lags=(0, 1, 3, 6),
):    
    #Prepare monthly sales  
    df = df_monthly_sales_data.copy()
    df["month"] = pd.to_datetime(df["month"])

    # normalize month to month start
    df["month"] = df["month"].dt.to_period("M").dt.to_timestamp()
    sku_lookup = (df[["sku_nbr", "sku_name", "sub_class", "region", "state_territory_code"]].drop_duplicates(subset=["sku_nbr"])    )
    df_sales = (df.groupby(["sku_nbr", "month"], as_index=False)["sales_units"].sum()    )
    df_sales = prepare_sales_features(df_sales)

    #Pull and prepare FRED
    df_houst = get_fred_series("HOUST")
    df_computsa = get_fred_series("COMPUTSA")
    df_fred = (df_houst.merge(df_computsa, on="month", how="outer").sort_values("month"))
    df_fred["month"] = df_fred["month"].dt.to_period("M").dt.to_timestamp()
    df_fred = add_fred_features(df_fred, "HOUST", lags=lags)
    df_fred = add_fred_features(df_fred, "COMPUTSA", lags=lags)

    fred_feature_cols = [
        c for c in df_fred.columns
        if c.startswith("HOUST_") or c.startswith("COMPUTSA_")
    ]
    
    # merge sales and FRED    
    df_model = df_sales.merge(
        df_fred[["month"] + fred_feature_cols],
        on="month",
        how="left",
    )

    sales_feature_cols = [
        "sales_level",
        "sales_pct_1m",
        "sales_pct_12m",
        "sales_roll3",
    ]
 
    # grid search    
    results = []

    for sku, g in df_model.groupby("sku_nbr"):
        for sales_col in sales_feature_cols:
            for fred_col in fred_feature_cols:
                temp = g[[sales_col, fred_col]].dropna()

                if len(temp) < min_obs:
                    continue

                # Avoid undefined corr when one side is constant
                if temp[sales_col].nunique() <= 1 or temp[fred_col].nunique() <= 1:
                    continue

                corr = temp[sales_col].corr(temp[fred_col])

                if pd.isna(corr):
                    continue

                results.append({
                    "sku_nbr": sku,
                    "sales_feature": sales_col,
                    "fred_feature": fred_col,
                    "correlation": corr,
                    "abs_correlation": abs(corr),
                    "n_obs": len(temp),
                })

    df_corr_results = pd.DataFrame(results)

    if df_corr_results.empty:
        raise ValueError("No valid correlations were computed. Check date alignment and data coverage.")

    #best correlation per SKU
    df_best_per_sku = (
        df_corr_results
        .sort_values(["sku_nbr", "abs_correlation"], ascending=[True, False])
        .groupby("sku_nbr", as_index=False)
        .first()
    )

    df_best_per_sku = df_best_per_sku.merge(sku_lookup, on="sku_nbr", how="left")    
    df_best_per_sku["fred_series"] = df_best_per_sku["fred_feature"].str.extract(r"^(HOUST|COMPUTSA)")[0]

    df_best_per_sku["fred_transform"] = df_best_per_sku["fred_feature"].str.extract(
        r"^(?:HOUST|COMPUTSA)_(level|pct_1m|pct_12m|roll3)"
    )[0]

    df_best_per_sku["lag_months"] = pd.to_numeric(
        df_best_per_sku["fred_feature"].str.extract(r"lag(\d+)")[0],
        errors="coerce"
    ).astype("Int64")

  
    # Summary tables  
    feature_summary = (df_best_per_sku.groupby(["fred_series", "fred_transform", "lag_months"], as_index=False).agg(
            sku_count=("sku_nbr", "count"),
            avg_corr=("correlation", "mean"),
            avg_abs_corr=("abs_correlation", "mean"),
            median_abs_corr=("abs_correlation", "median"),
        )
        .sort_values(["sku_count", "avg_abs_corr"], ascending=[False, False])
    )

    subclass_summary = (df_best_per_sku.groupby(["sub_class", "fred_series", "fred_transform", "lag_months"], as_index=False).agg(
            sku_count=("sku_nbr", "count"),
            avg_abs_corr=("abs_correlation", "mean"),
        )
        .sort_values(["sub_class", "sku_count", "avg_abs_corr"], ascending=[True, False, False])
    )

    region_summary = (df_best_per_sku.groupby(["region", "fred_series", "fred_transform", "lag_months"], as_index=False).agg(
            sku_count=("sku_nbr", "count"),
            avg_abs_corr=("abs_correlation", "mean"),
        )
        .sort_values(["region", "sku_count", "avg_abs_corr"], ascending=[True, False, False])
    )

    return df_corr_results, df_best_per_sku, feature_summary, subclass_summary, region_summary

df_corr_results, df_best_per_sku, feature_summary, subclass_summary, region_summary = run_sku_correlation_analysis(
    df_monthly_sales_data=df_monthly_sales_data,
    min_obs=18,
    lags=(0, 1, 3, 6),
)

print(df_best_per_sku.head(20))
print(feature_summary.head(20))
print(df_corr_results.sort_values("abs_correlation", ascending=False).head(20))

c:\Users\TobyWong\Desktop\UNCC\6211\advanced_business_analytics\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:2882: RuntimeWarning: invalid value encountered in subtract
  X -= avg[:, None]
c:\Users\TobyWong\Desktop\UNCC\6211\advanced_business_analytics\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:2887: RuntimeWarning: invalid value encountered in dot
  c = dot(X, X_T.conj())
c:\Users\TobyWong\Desktop\UNCC\6211\advanced_business_analytics\.venv\Lib\site-packages\numpy\_core\_methods.py:132: RuntimeWarning: invalid value encountered in reduce
  ret = umr_sum(arr, axis, dtype, out, keepdims, where=where)

    sku_nbr  sales_feature           fred_feature  correlation  \
0    110241    sales_roll3    COMPUTSA_roll3_lag3     0.646332
1    110269  sales_pct_12m    COMPUTSA_roll3_lag1     0.600660
2    110630    sales_roll3       HOUST_roll3_lag3     0.574733
3    110661    sales_roll3       HOUST_roll3_lag3     0.482470
4    110689  sales_pct_12m    COMPUTSA_roll3_lag6     0.579756
5    113053    sales_roll3            HOUST_roll3    -0.511099
6    120088  sales_pct_12m     HOUST_pct_12m_lag1     0.427168
7    134633    sales_roll3  COMPUTSA_pct_12m_lag3     0.646949
8    134634    sales_roll3  COMPUTSA_pct_12m_lag3     0.658114
9    142559  sales_pct_12m         COMPUTSA_roll3     0.696430
10   144650   sales_pct_1m   COMPUTSA_pct_1m_lag1     0.419363
11   144700   sales_pct_1m   COMPUTSA_pct_1m_lag1     0.386502
12   144745  sales_pct_12m       COMPUTSA_pct_12m    -0.605345
13   145587    sales_roll3  COMPUTSA_pct_12m_lag1     0.497463
14   145590  sales_pct_12m    COMPUTSA_roll3_lag1     0.641078
15   145668  sales_pct_12m    COMPUTSA_level_lag6     0.692370
16   145766  sales_pct_12m  COMPUTSA_pct_12m_lag6     0.661166
17   147075    sales_roll3  COMPUTSA_pct_12m_lag6    -0.423155
18   147103    sales_roll3       COMPUTSA_pct_12m    -0.630648
19   161035  sales_pct_12m  COMPUTSA_pct_12m_lag1    -0.547921

    abs_correlation  n_obs                            sku_name  \
0          0.646332     35             4"X1-1/2" DWV WYE HXHXH
1          0.600660     25        4"X1-1/2" DWV SANI TEE HXHXH
2          0.574733     35  2" DWV SOIL PIPE ADAPTER HX NO HUB
3          0.482470     35  3" DWV SOIL PIPE ADAPTER HX NO HUB
4          0.579756     25  4" DWV SOIL PIPE ADAPTER HX NO HUB
5          0.511099     35            6"X4" DWV SANI TEE HXHXH
6          0.427168     25         4"X10' D2729 SW SOLID DRAIN
7          0.646949     35  1-1/2" ABS DOUBLE SANI TEE HXHXHXH
8          0.658114     35          1-1/2" ABS DBL WYE HXHXHXH
9          0.696430     25              3/4" PVC PTRAP SPGXSPG
10         0.419363     36            1/2" PVC TEE FPTXFPTXFPT
11         0.386502     36            3/4" PVC TEE FPTXFPTXFPT
12         0.605345     25  1/2"X3/4" PVC FEMALE ADAPTER SXFPT
13         0.497463     35                  1-1/2" ABS CAP HUB
14         0.641078     25                      2" ABS CAP HUB
15         0.692370     25                      4" ABS CAP HUB
16         0.661166     25                      3" ABS CAP HUB
17         0.423155     35       6"X4" DWV FLUSH BUSHING SPGXH
18         0.630648     20            6" DWV CLEANOUT PLUG MPT
19         0.547921     25      1/2" CPVC COUPLING SXS 10 PACK

                    sub_class                  region state_territory_code  \
0    026-001-031-DWV FITTINGS           0001-MIDSOUTH                   AL
1    026-001-031-DWV FITTINGS           0001-MIDSOUTH                   AL
2    026-001-031-DWV FITTINGS           0001-MIDSOUTH                   AL
3    026-001-031-DWV FITTINGS          0024-SOUTHEAST                   AL
4    026-001-031-DWV FITTINGS           0001-MIDSOUTH                   AL
5    026-001-031-DWV FITTINGS           0001-MIDSOUTH                   AL
6      026-001-033-SEWER PIPE     0034-PAC MTN DESERT                   AZ
7    026-001-005-ABS FITTINGS  0012-PACIFIC NORTHWEST                   AK
8    026-001-005-ABS FITTINGS  0012-PACIFIC NORTHWEST                   AK
9    026-001-003-PVC FITTINGS  0012-PACIFIC NORTHWEST                   AK
10   026-001-003-PVC FITTINGS  0012-PACIFIC NORTHWEST                   AK
11   026-001-003-PVC FITTINGS  0012-PACIFIC NORTHWEST                   AK
12   026-001-003-PVC FITTINGS  0012-PACIFIC NORTHWEST                   AK
13   026-001-005-ABS FITTINGS  0012-PACIFIC NORTHWEST                   AK
14   026-001-005-ABS FITTINGS  0012-PACIFIC NORTHWEST                   AK
15   026-001-005-ABS FITTINGS  0012-PACIFIC NORTHWEST                   AK
16   026-001-005-ABS FITTINGS  0012-PACIFIC NORTHWEST                   AK
17   026-001-031-DWV FITTINGS     0034-PAC MTN DESERT                   AZ
18   026-001-031-DWV FITTINGS           0001-MIDSOUTH                   GA
19  026-001-013-CPVC FITTINGS  0012-PACIFIC NORTHWEST                   AK

   fred_series fred_transform  lag_months
0     COMPUTSA          roll3           3
1     COMPUTSA          roll3           1
2        HOUST          roll3           3
3        HOUST          roll3           3
4     COMPUTSA          roll3           6
5        HOUST          roll3        <NA>
6        HOUST        pct_12m           1
7     COMPUTSA        pct_12m           3
8     COMPUTSA        pct_12m           3
9     COMPUTSA          roll3        <NA>
10    COMPUTSA         pct_1m           1
11    COMPUTSA         pct_1m           1
12    COMPUTSA        pct_12m        <NA>
13    COMPUTSA        pct_12m           1
14    COMPUTSA          roll3           1
15    COMPUTSA          level           6
16    COMPUTSA        pct_12m           6
17    COMPUTSA        pct_12m           6
18    COMPUTSA        pct_12m        <NA>
19    COMPUTSA        pct_12m           1
   fred_series fred_transform  lag_months  sku_count  avg_corr  avg_abs_corr  \
11    COMPUTSA          roll3           6        117  0.573228      0.653667
5     COMPUTSA        pct_12m           6         61  0.549634      0.618715
20       HOUST          roll3           3         60  0.318203      0.533278
2     COMPUTSA          level           6         56  0.623261      0.623261
9     COMPUTSA          roll3           1         47  0.481005      0.646047
10    COMPUTSA          roll3           3         43  0.443093      0.633928
3     COMPUTSA        pct_12m           1         35 -0.030641      0.585405
4     COMPUTSA        pct_12m           3         33  0.377080      0.616790
16       HOUST        pct_12m           6         23 -0.129706      0.534648
19       HOUST          roll3           1         19  0.453250      0.582315
8     COMPUTSA         pct_1m           6         16  0.486843      0.536086
14       HOUST        pct_12m           1         14 -0.360707      0.492679
21       HOUST          roll3           6         10 -0.033609      0.502375
15       HOUST        pct_12m           3          9 -0.071798      0.553226
0     COMPUTSA          level           1          6  0.412642      0.597356
6     COMPUTSA         pct_1m           1          6  0.465601      0.465601
12       HOUST          level           3          4 -0.270320      0.520433
13       HOUST          level           6          3 -0.180482      0.468831
1     COMPUTSA          level           3          2  0.541564      0.541564
7     COMPUTSA         pct_1m           3          2 -0.473288      0.473288

    median_abs_corr
11         0.650466
5          0.631823
20         0.536621
2          0.611294
9          0.645037
10         0.617948
3          0.575733
4          0.621769
16         0.531965
19         0.577034
8          0.511923
14         0.490644
21         0.520587
15         0.556300
0          0.595022
6          0.446297
12         0.507478
13         0.432525
1          0.541564
7          0.473288
           sku_nbr  sales_feature         fred_feature  correlation  \
117996  1011642227    sales_roll3  COMPUTSA_roll3_lag0    -0.922693
117983  1011642227    sales_roll3       COMPUTSA_roll3    -0.922693
87598       760407    sales_roll3  COMPUTSA_roll3_lag3     0.897999
117997  1011642227    sales_roll3  COMPUTSA_roll3_lag1    -0.889815
87239       756656  sales_pct_12m  COMPUTSA_roll3_lag6     0.884850
117876  1011642044    sales_roll3  COMPUTSA_roll3_lag0    -0.872664
117863  1011642044    sales_roll3       COMPUTSA_roll3    -0.872664
87557       760407  sales_pct_12m  COMPUTSA_roll3_lag1     0.867785
95956       847703  sales_pct_12m  COMPUTSA_roll3_lag0     0.867545
95943       847703  sales_pct_12m       COMPUTSA_roll3     0.867545
117877  1011642044    sales_roll3  COMPUTSA_roll3_lag1    -0.866283
57397       426540  sales_pct_12m  COMPUTSA_roll3_lag1    -0.866013
57398       426540  sales_pct_12m  COMPUTSA_roll3_lag3    -0.855420
117916  1011642227    sales_level  COMPUTSA_roll3_lag0    -0.849264
117903  1011642227    sales_level       COMPUTSA_roll3    -0.849264
69319       605122  sales_pct_12m  COMPUTSA_roll3_lag6     0.845332
95957       847703  sales_pct_12m  COMPUTSA_roll3_lag1     0.843635
87543       760407  sales_pct_12m       COMPUTSA_roll3     0.837917
87556       760407  sales_pct_12m  COMPUTSA_roll3_lag0     0.837917
32107       193860  sales_pct_12m  COMPUTSA_level_lag6     0.837672

        abs_correlation  n_obs
117996         0.922693     20
117983         0.922693     20
87598          0.897999     35
117997         0.889815     20
87239          0.884850     25
117876         0.872664     18
117863         0.872664     18
87557          0.867785     25
95956          0.867545     25
95943          0.867545     25
117877         0.866283     18
57397          0.866013     25
57398          0.855420     25
117916         0.849264     22
117903         0.849264     22
69319          0.845332     25
95957          0.843635     25
87543          0.837917     25
87556          0.837917     25
32107          0.837672     25

In [42]:
df_final_coefficients = df_best_per_sku[
    ["sku_nbr", "sku_name", "correlation", "abs_correlation", "sales_feature", "fred_feature", "n_obs"]
].copy()

print(df_final_coefficients)

        sku_nbr                            sku_name  correlation  \
0        110241             4"X1-1/2" DWV WYE HXHXH     0.646332
1        110269        4"X1-1/2" DWV SANI TEE HXHXH     0.600660
2        110630  2" DWV SOIL PIPE ADAPTER HX NO HUB     0.574733
3        110661  3" DWV SOIL PIPE ADAPTER HX NO HUB     0.482470
4        110689  4" DWV SOIL PIPE ADAPTER HX NO HUB     0.579756
..          ...                                 ...          ...
773  1006145870           2 DWV FLUSH CLEANOUT PLUG    -0.360516
774  1007427211         1/2 SCH 40 DEEP SOCKET CPLG     0.788857
775  1007540445          1" SCH 40 DEEP SOCKET CPLG     0.609280
776  1011642044        1 1/2 IN. ABS EXT SWVL ADPTR    -0.872664
777  1011642227       1 1/2  ABS SWVL PLUG ADA WSHR    -0.922693

     abs_correlation  sales_feature         fred_feature  n_obs
0           0.646332    sales_roll3  COMPUTSA_roll3_lag3     35
1           0.600660  sales_pct_12m  COMPUTSA_roll3_lag1     25
2           0.574733    sales_roll3     HOUST_roll3_lag3     35
3           0.482470    sales_roll3     HOUST_roll3_lag3     35
4           0.579756  sales_pct_12m  COMPUTSA_roll3_lag6     25
..               ...            ...                  ...    ...
773         0.360516    sales_roll3     COMPUTSA_pct_12m     35
774         0.788857    sales_roll3  COMPUTSA_roll3_lag3     35
775         0.609280    sales_roll3  COMPUTSA_roll3_lag3     35
776         0.872664    sales_roll3       COMPUTSA_roll3     18
777         0.922693    sales_roll3       COMPUTSA_roll3     20

[778 rows x 7 columns]

In [ ]:
# df_final_coefficients.to_csv("data/correlation_coefficients.csv")

In [45]:
def get_fred_series(series_id: str) -> pd.DataFrame:
    params = {
        "series_id": series_id,
        "api_key": API_KEY,
        "file_type": "json",
    }
    response = requests.get(BASE_URL, params=params, timeout=30)
    response.raise_for_status()

    data = response.json()
    df = pd.DataFrame(data["observations"])[["date", "value"]]
    df["date"] = pd.to_datetime(df["date"])
    df["value"] = pd.to_numeric(df["value"], errors="coerce")
    return df.rename(columns={"date": "month", "value": series_id})


def simple_regression_beta(x: pd.Series, y: pd.Series):
    temp = pd.concat([x, y], axis=1).dropna()

    if len(temp) < 12:
        return np.nan, np.nan, len(temp)

    x_clean = temp.iloc[:, 0]
    y_clean = temp.iloc[:, 1]

    if x_clean.nunique() <= 1 or y_clean.nunique() <= 1:
        return np.nan, np.nan, len(temp)

    beta = np.cov(x_clean, y_clean, ddof=1)[0, 1] / np.var(x_clean, ddof=1)
    alpha = y_clean.mean() - beta * x_clean.mean()

    return beta, alpha, len(temp)


# -----------------------
# 1. Prepare your sales
# -----------------------
df = df_monthly_sales_data.copy()
df["month"] = pd.to_datetime(df["month"]).dt.to_period("M").dt.to_timestamp()

df_sales = (
    df.groupby(["sku_nbr", "month"], as_index=False)["sales_units"]
    .sum()
)

sku_lookup = (
    df[["sku_nbr", "sku_name", "sub_class", "region", "state_territory_code"]]
    .drop_duplicates(subset=["sku_nbr"])
)

# -----------------------
# 2. Pull FRED data
# -----------------------
df_houst = get_fred_series("HOUST")
df_computsa = get_fred_series("COMPUTSA")

df_fred = (
    df_houst.merge(df_computsa, on="month", how="outer")
    .sort_values("month")
)

df_fred["month"] = df_fred["month"].dt.to_period("M").dt.to_timestamp()

# -----------------------
# 3. Merge
# -----------------------
df_model = df_sales.merge(df_fred, on="month", how="left")

# -----------------------
# 4. Per-SKU betas
# -----------------------
results = []

for sku, g in df_model.groupby("sku_nbr"):
    beta_computsa, alpha_computsa, n1 = simple_regression_beta(
        g["COMPUTSA"], g["sales_units"]
    )
    beta_houst, alpha_houst, n2 = simple_regression_beta(
        g["HOUST"], g["sales_units"]
    )

    corr_computsa = g["sales_units"].corr(g["COMPUTSA"])
    corr_houst = g["sales_units"].corr(g["HOUST"])

    results.append({
        "sku_nbr": sku,
        "beta_computsa": beta_computsa,
        "alpha_computsa": alpha_computsa,
        "corr_computsa": corr_computsa,
        "n_obs_computsa": n1,
        "beta_houst": beta_houst,
        "alpha_houst": alpha_houst,
        "corr_houst": corr_houst,
        "n_obs_houst": n2,
    })

df_sku_betas = pd.DataFrame(results).merge(sku_lookup, on="sku_nbr", how="left")

print(df_sku_betas.head())

c:\Users\TobyWong\Desktop\UNCC\6211\advanced_business_analytics\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3015: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
c:\Users\TobyWong\Desktop\UNCC\6211\advanced_business_analytics\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:2888: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
c:\Users\TobyWong\Desktop\UNCC\6211\advanced_business_analytics\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:2888: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
c:\Users\TobyWong\Desktop\UNCC\6211\advanced_business_analytics\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3023: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
c:\Users\TobyWong\Desktop\UNCC\6211\advanced_business_analytics\.venv\Lib\site-packages\numpy\lib\_function_base_impl.py:3024: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

   sku_nbr  beta_computsa  alpha_computsa  corr_computsa  n_obs_computsa  \
0   110241       0.135968      158.137475       0.238997              37
1   110269       0.048480      915.139494       0.034823              37
2   110630      -0.228148     1476.495289      -0.166250              37
3   110661      -0.038102      631.979692      -0.051361              37
4   110689      -0.017911      638.241346      -0.021279              37

   beta_houst  alpha_houst  corr_houst  n_obs_houst  \
0    0.023285   332.870769    0.031403           37
1    0.108931   838.008309    0.060032           37
2   -0.100652  1268.627127   -0.056273           37
3    0.037478   522.042902    0.038760           37
4    0.096653   477.048565    0.088098           37

                             sku_name                 sub_class  \
0             4"X1-1/2" DWV WYE HXHXH  026-001-031-DWV FITTINGS
1        4"X1-1/2" DWV SANI TEE HXHXH  026-001-031-DWV FITTINGS
2  2" DWV SOIL PIPE ADAPTER HX NO HUB  026-001-031-DWV FITTINGS
3  3" DWV SOIL PIPE ADAPTER HX NO HUB  026-001-031-DWV FITTINGS
4  4" DWV SOIL PIPE ADAPTER HX NO HUB  026-001-031-DWV FITTINGS

           region state_territory_code
0   0001-MIDSOUTH                   AL
1   0001-MIDSOUTH                   AL
2   0001-MIDSOUTH                   AL
3  0024-SOUTHEAST                   AL
4   0001-MIDSOUTH                   AL

In [46]:
df_sku_betas["best_driver"] = np.where(
    df_sku_betas["corr_computsa"].abs() >= df_sku_betas["corr_houst"].abs(),
    "COMPUTSA",
    "HOUST"
)

df_sku_betas["best_beta"] = np.where(
    df_sku_betas["best_driver"] == "COMPUTSA",
    df_sku_betas["beta_computsa"],
    df_sku_betas["beta_houst"]
)

df_sku_betas["best_corr"] = np.where(
    df_sku_betas["best_driver"] == "COMPUTSA",
    df_sku_betas["corr_computsa"],
    df_sku_betas["corr_houst"]
)

print(df_sku_betas[[
    "sku_nbr", "sku_name", "best_driver", "best_beta", "best_corr"
]].head())

   sku_nbr                            sku_name best_driver  best_beta  \
0   110241             4"X1-1/2" DWV WYE HXHXH    COMPUTSA   0.135968
1   110269        4"X1-1/2" DWV SANI TEE HXHXH       HOUST   0.108931
2   110630  2" DWV SOIL PIPE ADAPTER HX NO HUB    COMPUTSA  -0.228148
3   110661  3" DWV SOIL PIPE ADAPTER HX NO HUB    COMPUTSA  -0.038102
4   110689  4" DWV SOIL PIPE ADAPTER HX NO HUB       HOUST   0.096653

   best_corr
0   0.238997
1   0.060032
2  -0.166250
3  -0.051361
4   0.088098

In [47]:
df_sku_betas.to_csv("data/correlation_coefficients.csv")