In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
import os
# Define the local folder filename
csv_filename = 'Queryclassproject_Full_2026-04-02.csv'
# Read the CSV file from the specified path
full_path = os.path.join(r'data', csv_filename)
df = pd.read_csv(full_path)
df.head()

,month,sku name,sku nbr,state territory code,sub class,region,sales units,sales $
0,Fiscal Period 12 of 2025,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0,62.93
1,Fiscal Period 3 of 2026,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,-1.0,-13.11
2,Fiscal Period 2 of 2025,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0,65.55
3,Fiscal Period 1 of 2026,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,3.0,39.33
4,Fiscal Period 10 of 2025,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0,65.55

In [8]:
df['month_year'] = df['month'].str[-4:]
df['month_number'] = df['month'].str.extract(r'Fiscal Period (\d+)').astype(int)
df_clean = df.drop(columns=['month'])
df_clean['month'] = (df_clean['month_number'].astype(str) + '-' + pd.to_datetime(df_clean['month_year']).dt.strftime('%b-%Y'))
df_clean['month'] = pd.to_datetime('1-' + df_clean['month_number'].astype(str) + '-' + df_clean['month_year'].astype(str), format='%d-%m-%Y')
df_clean = df_clean.dropna(subset=['sales units'])
df_clean = df_clean.drop(columns = ['sales $','month_number','month_year',])
df_clean.head(5)

,sku name,sku nbr,state territory code,sub class,region,sales units,month
0,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0,2025-12-01
1,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,-1.0,2026-03-01
2,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0,2025-02-01
3,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,3.0,2026-01-01
4,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0,2025-10-01

In [9]:
df_clean.to_csv('data/monthly_sales_data.csv', index=False)