***Notebook to create SKU specific data for top 10 products***

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [ ]:
# Define the local folder filename
csv_filename = 'cltpipe_homedepot_data.csv'
# Read the CSV file from the specified path
full_path = os.path.join(r'C:\Users\tobia\OneDrive\Desktop\School\advanced_business_analytics\data', csv_filename)
df = pd.read_csv(full_path)
df.head()

,month,sku name,sku nbr,state territory code,sub class,region,sales units,sales $
0,Fiscal Period 12 of 2025,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0,62.93
1,Fiscal Period 3 of 2026,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,-1.0,-13.11
2,Fiscal Period 2 of 2025,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0,65.55
3,Fiscal Period 1 of 2026,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,3.0,39.33
4,Fiscal Period 10 of 2025,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,AK,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0,65.55

In [3]:
df.count()

month                   1222131
sku name                1222131
sku nbr                 1222131
state territory code    1222131
sub class               1222131
region                  1222131
sales units             1083745
sales $                 1083745
dtype: int64

In [4]:
df_clean = df.drop(columns=['state territory code', 'sales $'])
df_clean.head(1)

,month,sku name,sku nbr,sub class,region,sales units
0,Fiscal Period 12 of 2025,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0

In [5]:
df_clean['month_year'] = df_clean['month'].str[-4:]
df_clean['month_number'] = df_clean['month'].str.extract(r'Fiscal Period (\d+)').astype(int)
df_clean = df_clean.drop(columns=['month'])
df_clean['month'] = (df_clean['month_number'].astype(str) + '-' + pd.to_datetime(df_clean['month_year']).dt.strftime('%b-%Y'))
df_clean['month'] = pd.to_datetime('1-' + df_clean['month_number'].astype(str) + '-' + df_clean['month_year'].astype(str), format='%d-%m-%Y')
df_clean = df_clean.dropna(subset=['sales units'])
df_clean.head(5)

,sku name,sku nbr,sub class,region,sales units,month_year,month_number,month
0,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0,2025,12,2025-12-01
1,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,-1.0,2026,3,2026-03-01
2,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0,2025,2,2025-02-01
3,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,3.0,2026,1,2026-01-01
4,"1-1/2"" ABS DOUBLE SANI TEE HXHXHXH",134633,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0,2025,10,2025-10-01

In [6]:
df_clean = df_clean.assign(sku=df_clean['sku name'].str.replace(r"[\",\-']", "", regex=True))
df_clean = df_clean.drop(columns=['sku name'])
df_clean['sku'] = df_clean['sku'].str.replace(' ', '_')
df_clean = df_clean.rename(columns={'sku': 'sku name'})
df_clean.head()

,sku nbr,sub class,region,sales units,month_year,month_number,month,sku name
0,134633,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0,2025,12,2025-12-01,11/2_ABS_DOUBLE_SANI_TEE_HXHXHXH
1,134633,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,-1.0,2026,3,2026-03-01,11/2_ABS_DOUBLE_SANI_TEE_HXHXHXH
2,134633,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0,2025,2,2025-02-01,11/2_ABS_DOUBLE_SANI_TEE_HXHXHXH
3,134633,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,3.0,2026,1,2026-01-01,11/2_ABS_DOUBLE_SANI_TEE_HXHXHXH
4,134633,026-001-005-ABS FITTINGS,0012-PACIFIC NORTHWEST,5.0,2025,10,2025-10-01,11/2_ABS_DOUBLE_SANI_TEE_HXHXHXH

In [7]:
df_clean['sub class'] = df_clean['sub class'].str.replace('-', '_')
df_clean['region'] = df_clean['region'].str.replace('-', '_')

In [8]:
df_top_10_sku = df_clean.copy()
df_top_10_sku = df_top_10_sku['sku name'].value_counts().reset_index()
df_top_10_sku.columns = ['sku', 'count of sku']
df_top_10_sku.head(10)

                                   sku  count of sku
0    3/4_SCH_40_90_DEG_ELBOW_SXS_35_PK          3431
1     3/4_SIDE_OUTLET_90_DEGREE_SOCKET          3407
2       3/4_SCH_40_TEE_SXSXS_(20_PACK)          3401
3     3/4_PVC_COUPLING_DEEP_SOCKET_SXS          3394
4             11/4X2FT_PVC_SCH_40_PIPE          3369
5    3/4_SCH_40_COUPLING_SXS_(25_PACK)          3369
6  1_PVC_SIDE_OUTLET90_DEG_ELBOW_SXSXS          3336
7         3/4_PVC_RUNNING_TRAP_SPGXSPG          3304
8            1/2X2_FLOWGUARD_GOLD_CPVC          3262
9        11/2X2_PVC_MALE_ADAPTER_MPTXS          3249

In [9]:
top_10_skus = df_top_10_sku['sku'].head(10).to_dict()
top_10_skus

{0: '3/4_SCH_40_90_DEG_ELBOW_SXS_35_PK',
 1: '3/4_SIDE_OUTLET_90_DEGREE_SOCKET',
 2: '3/4_SCH_40_TEE_SXSXS_(20_PACK)',
 3: '3/4_PVC_COUPLING_DEEP_SOCKET_SXS',
 4: '11/4X2FT_PVC_SCH_40_PIPE',
 5: '3/4_SCH_40_COUPLING_SXS_(25_PACK)',
 6: '1_PVC_SIDE_OUTLET90_DEG_ELBOW_SXSXS',
 7: '3/4_PVC_RUNNING_TRAP_SPGXSPG',
 8: '1/2X2_FLOWGUARD_GOLD_CPVC',
 9: '11/2X2_PVC_MALE_ADAPTER_MPTXS'}

In [10]:
df_top_10_sku_data = df_clean[df_clean["sku name"].isin(top_10_skus.values())].copy()
df_top_10_sku_data = df_top_10_sku_data[["month", "sku name", "sku nbr", "sub class", "region", "sales units"]]
df_top_10_sku_data = df_top_10_sku_data.rename(columns={"sku name": "sku_name", "sku nbr": "sku_num", "sub class": "sub_class", "sales units": "sales_units"})
df_top_10_sku_data.head()

,month,sku_name,sku_num,sub_class,region,sales_units
843,2024-04-01,1/2X2_FLOWGUARD_GOLD_CPVC,206041,026_001_012_CPVC PIPE,0012_PACIFIC NORTHWEST,3.0
844,2025-09-01,1/2X2_FLOWGUARD_GOLD_CPVC,206041,026_001_012_CPVC PIPE,0012_PACIFIC NORTHWEST,12.0
845,2025-02-01,1/2X2_FLOWGUARD_GOLD_CPVC,206041,026_001_012_CPVC PIPE,0012_PACIFIC NORTHWEST,4.0
846,2025-04-01,1/2X2_FLOWGUARD_GOLD_CPVC,206041,026_001_012_CPVC PIPE,0012_PACIFIC NORTHWEST,8.0
847,2024-12-01,1/2X2_FLOWGUARD_GOLD_CPVC,206041,026_001_012_CPVC PIPE,0012_PACIFIC NORTHWEST,5.0

In [11]:
df_top_10_sku_data.count()

month          33522
sku_name       33522
sku_num        33522
sub_class      33522
region         33522
sales_units    33522
dtype: int64

In [25]:
df_masked = df_top_10_sku_data.copy()
df_masked = df_masked.drop(columns=['sub_class'])
df_masked['region'] = df_masked['region'].str[5:]
df_masked['region'] = df_masked['region'].str.replace(' ', '_')
df_masked.head()

,month,sku_name,sku_num,region,sales_units
843,2024-04-01,1/2X2_FLOWGUARD_GOLD_CPVC,206041,PACIFIC_NORTHWEST,3.0
844,2025-09-01,1/2X2_FLOWGUARD_GOLD_CPVC,206041,PACIFIC_NORTHWEST,12.0
845,2025-02-01,1/2X2_FLOWGUARD_GOLD_CPVC,206041,PACIFIC_NORTHWEST,4.0
846,2025-04-01,1/2X2_FLOWGUARD_GOLD_CPVC,206041,PACIFIC_NORTHWEST,8.0
847,2024-12-01,1/2X2_FLOWGUARD_GOLD_CPVC,206041,PACIFIC_NORTHWEST,5.0

In [26]:
col_name = 'sales_units' 

noise = np.random.normal(loc=0, scale=df_masked[col_name].std() * 0.001, size=df_masked[col_name].shape[0])
df_masked[col_name] = df_masked[col_name] + noise
df_masked.head()

,month,sku_name,sku_num,region,sales_units
843,2024-04-01,1/2X2_FLOWGUARD_GOLD_CPVC,206041,PACIFIC_NORTHWEST,2.418678
844,2025-09-01,1/2X2_FLOWGUARD_GOLD_CPVC,206041,PACIFIC_NORTHWEST,12.006578
845,2025-02-01,1/2X2_FLOWGUARD_GOLD_CPVC,206041,PACIFIC_NORTHWEST,4.480735
846,2025-04-01,1/2X2_FLOWGUARD_GOLD_CPVC,206041,PACIFIC_NORTHWEST,7.926598
847,2024-12-01,1/2X2_FLOWGUARD_GOLD_CPVC,206041,PACIFIC_NORTHWEST,4.778459

In [27]:
sku_map = {
    '3/4_SCH_40_90_DEG_ELBOW_SXS_35_PK': 'PVC-ELB90-0.75-S40-SXS [35pk]',
    '3/4_SIDE_OUTLET_90_DEGREE_SOCKET': 'PVC-S-ELB90-0.75-SOC',
    '3/4_SCH_40_TEE_SXSXS_(20_PACK)': 'PVC-TEE-0.75-S40-SXSXS [20pk]',
    '3/4_PVC_COUPLING_DEEP_SOCKET_SXS': 'PVC-CPL-0.75-DS-SXS',
    '11/4X2FT_PVC_SCH_40_PIPE': 'PVC-PIPE-1.25-S40 [2FT]',
    '3/4_SCH_40_COUPLING_SXS_(25_PACK)': 'PVC-CPL-0.75-S40-SXS [25pk]',
    '1_PVC_SIDE_OUTLET90_DEG_ELBOW_SXSXS': 'PVC-S-ELB90-1.0-SXSXS',
    '3/4_PVC_RUNNING_TRAP_SPGXSPG': 'PVC-TRP-0.75-SPG-SPG',
    '1/2X2_FLOWGUARD_GOLD_CPVC': 'CPVC-GLD-0.5-PIPE [2FT]',
    '11/2X2_PVC_MALE_ADAPTER_MPTXS': 'PVC-ADP-1.5x2-MPT-SOC'
}

df_masked['sku_name_masked'] = df_masked['sku_name'].map(sku_map)

df_masked = df_masked.drop(columns=['sku_name'])

df_masked = df_masked.rename(columns={'sku_name_masked': 'sku_name'})

print(df_masked['sku_name'].head())

843    CPVC-GLD-0.5-PIPE [2FT]
844    CPVC-GLD-0.5-PIPE [2FT]
845    CPVC-GLD-0.5-PIPE [2FT]
846    CPVC-GLD-0.5-PIPE [2FT]
847    CPVC-GLD-0.5-PIPE [2FT]
Name: sku_name, dtype: str

In [28]:
df_masked.head()

,month,sku_num,region,sales_units,sku_name
843,2024-04-01,206041,PACIFIC_NORTHWEST,2.418678,CPVC-GLD-0.5-PIPE [2FT]
844,2025-09-01,206041,PACIFIC_NORTHWEST,12.006578,CPVC-GLD-0.5-PIPE [2FT]
845,2025-02-01,206041,PACIFIC_NORTHWEST,4.480735,CPVC-GLD-0.5-PIPE [2FT]
846,2025-04-01,206041,PACIFIC_NORTHWEST,7.926598,CPVC-GLD-0.5-PIPE [2FT]
847,2024-12-01,206041,PACIFIC_NORTHWEST,4.778459,CPVC-GLD-0.5-PIPE [2FT]

In [29]:
df_masked.count()

month          33522
sku_num        33522
region         33522
sales_units    33522
sku_name       33522
dtype: int64

In [30]:
df_masked = df_masked[['month', 'sku_name', 'sku_num', 'region', 'sales_units']]
df_masked.head()

,month,sku_name,sku_num,region,sales_units
843,2024-04-01,CPVC-GLD-0.5-PIPE [2FT],206041,PACIFIC_NORTHWEST,2.418678
844,2025-09-01,CPVC-GLD-0.5-PIPE [2FT],206041,PACIFIC_NORTHWEST,12.006578
845,2025-02-01,CPVC-GLD-0.5-PIPE [2FT],206041,PACIFIC_NORTHWEST,4.480735
846,2025-04-01,CPVC-GLD-0.5-PIPE [2FT],206041,PACIFIC_NORTHWEST,7.926598
847,2024-12-01,CPVC-GLD-0.5-PIPE [2FT],206041,PACIFIC_NORTHWEST,4.778459

In [ ]:
df_masked.to_csv('data/home_depot_sales_data.csv', index=False)